language: node_js
node_js:
      - "node"
script:
      - npm test 
      - node_modules/.bin/jshint src
      - node_modules/.bin/jsdoc src

deploy : 
      provider : pages
      skip-cleanup : true
      github-token : $GItToken 
      keep-history : true
